[package]
name = "syndication_format"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/SuperioOne/syndication_format"
repository = "https://github.com/SuperioOne/syndication_format"

[features]
default = ["std"]
avx512 = []
std = []
